return {
  LinearLayout,
  id: "root",
  layout_width: "match_parent",
  layout_height: "wrap_content",
  orientation: "vertical",
  paddingLeft: "22dp",
  paddingTop: "18dp",
  paddingRight: "22dp",
  paddingBottom: "15dp",

  {
    TextView,
    id: "title",
    layout_width: "match_parent",
    layout_height: "wrap_content",
    text: "Create New App",
    textSize: "22sp",
    paddingBottom: "13dp",
  },

  {
    EditText,
    id: "appName",
    layout_width: "match_parent",
    layout_height: "wrap_content",
    hint: "App name",
    textSize: "16sp",
    singleLine: true,
  },

  {
    EditText,
    id: "packageName",
    layout_width: "match_parent",
    layout_height: "wrap_content",
    hint: "Package name",
    text: "com.example.myapp",
    textSize: "16sp",
    singleLine: true,
    layout_marginTop: "12dp",
  },

  {
    LinearLayout,
    id: "buttons",
    layout_width: "match_parent",
    layout_height: "wrap_content",
    orientation: "horizontal",
    gravity: "right",
    paddingTop: "10dp",

    {
      TextView,
      id: "cancel",
      layout_width: "wrap_content",
      layout_height: "wrap_content",
      text: "Cancel",
      textSize: "16sp",
      textColor: "#808080",
      gravity: "center",
      paddingLeft: "18dp",
      paddingTop: "10dp",
      paddingRight: "18dp",
      paddingBottom: "10dp",
    },

    {
      TextView,
      id: "create",
      layout_width: "wrap_content",
      layout_height: "wrap_content",
      text: "Create",
      textSize: "16sp",
      textColor: "#1E64DC",
      gravity: "center",
      paddingLeft: "18dp",
      paddingTop: "10dp",
      paddingRight: "18dp",
      paddingBottom: "10dp",
    },
  },
}