return {
  FrameLayout,
  layout_height: "match_parent",
  layout_width: "85%w",
  layout_gravity: "left",
  background: theme.background,
  {
    LinearLayout,
    layout_height: "match_parent",
    layout_width: "match_parent",
    orientation: "vertical",
    {
      ImageView,
      layout_height: "24%h",
      layout_width: "match_parent",
      scaleType: "fitXY",
      src: "icons/background.png",
    },
    {
      ListView,
      layout_height: "match_parent",
      layout_width: "match_parent",
      id: "drawer_list",
      layout_marginTop: "10dp",
      dividerHeight: "0",
    },
  },
  {
    LinearLayout,
    layout_height: "5%h",
    layout_width: "match_parent",
    orientation: "horizontal",
    background: ui_utils.strokeBg(theme.background, 1, theme.text, 1),
    layout_gravity: "bottom",
    gravity: "center",
    {
      ImageView,
      layout_width: "32dp",
      layout_height: "32dp",
      colorFilter: "#777777",
      src: "icons/ic_search.png",
      layout_weight: 1,
    },
    {
      ImageView,
      id: "drawer_add",
      layout_width: "32dp",
      layout_height: "32dp",
      colorFilter: "#777777",
      src: "icons/add.png",
      layout_weight: 1,
    },
    {
      ImageView,
      layout_width: "32dp",
      layout_height: "32dp",
      colorFilter: "#777777",
      src: "icons/ic_up.png",
      layout_weight: 1,
    },
  },
}