return {
  FrameLayout,
  {
    LinearLayout,
    layout_height: "match_parent",
    layout_width: "match_parent",
    orientation: "vertical",
  
    {
      CardView,
      layout_height: "wrap_content",
      backgroundColor: theme.colorPrimary,
      radius: "0dp",
      CardElevation: "3dp",
      layout_width: "match_parent",
      
      {
        LinearLayout,
        layout_width: "match_parent",
        layout_marginTop: result,
        {
          LinearLayout,
          orientation: "horizontal",
          gravity: "center",
          layout_height: "56dp",
          layout_width: "match_parent",
          
          {
            LinearLayout,
            layout_height: "match_parent",
            gravity: "center",
            
            {
              CardView,
              layout_height: "80dp",
              PreventCornerOverlap: false,
              layout_marginLeft: "-15dp",
              CardElevation: "0dp",
              radius: "40dp",
              UseCompatPadding: false,
              background: "#00000000",
              layout_width: "80dp",
              {
                ImageView,
                layout_height: "match_parent",
                layout_margin: "-10dp",
                id: "btn",
                padding: "26dp",
                src: "icons/ic_drawer.png",
                colorFilter: 0xFFFFFFFFFF,
                layout_width: "match_parent",
              },
            },
          },
          
          {
            TextView,
            id: "title",
            gravity: "center|left",
            singleLine: true,
            layout_marginLeft: "-15dp",
            layout_width: "match_parent",
            textSize: "19dp",
            ellipsize: "end",
            layout_height: "match_parent",
            layout_weight: "1",
            textColor: "#FFFFFF",
          },
                    {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-17dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "save",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icons/save.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-17dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "undo",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icons/undo.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-19dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "redo",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icons/redo.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-10dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "btnmenu",
              colorFilter: 0xFFFFFFFFFF,
              padding: "20dp",
              src: "icons/ic_dotsmenu.png",
              layout_width: "match_parent",
            },
          },
        },
      },
    },
    {
      LinearLayout,
      layout_height: "match_parent",
      layout_width: "match_parent",
      orientation: "vertical",
      {
        LinearLayout,
        layout_height: "40dp",
        layout_width: "match_parent",
        backgroundColor: theme.colorPrimary,
        orientation: "horizontal",
        {
          TextView,
          id: "filename",
          layout_height: "match_parent",
          layout_width: "30%w",
          //layout_weight: "1",
          gravity: "center",
          text: "Home",
          textColor: "#FFFFFF",
          layout_margin: "4dp"
        },
      },
      {
        CodeEditor,
        id: "editor",
        layout_width: "match_parent",
        layout_height: "match_parent",
        textSize: "10sp",
        dark: theme.isDarkMode()
      }
    },
  },
  {
    LinearLayout,
    layout_gravity: "bottom",
    orientation: "vertical",
    layout_width: "match_parent",
    {
      ImageView,
      id: "run",
      src: "icons/run.png",
      layout_width: "54dp",
      layout_height: "54dp",
      layout_gravity: "right",
      colorFilter: "#FFFFFFFF",
      background: ui_utils.roundBg(0xFFF85149, 32),
      layout_margin: "12dp"
    }, 
    
    {
      HorizontalScrollView,
      id: "symbolBar",
      layout_width: "match_parent",
      layout_height: "75px",
      fillViewport: true,
      horizontalScrollBarEnabled: false,
      background: ui_utils.strokeBg(theme.background, 1, theme.secondary, 1),

      {
        LinearLayout,
        id: "symbolBar",
        orientation: "horizontal",
        layout_width: "wrap_content",
        layout_height: "match_parent",
        gravity: "center_vertical",
      },
    },
    {
      LinearLayout,
      id: "findreplace",
      visibility: "gone",
      orientation: "vertical",
      paddingLeft: "16dp",
      paddingRight: "8dp",
      background: theme.background,
      
      // FIND
      {
        LinearLayout,
        orientation: "vertical",
        layout_width: "match_parent",
        layout_height: "52dp",
        
        {
          LinearLayout,
          orientation: "horizontal",
          layout_height: "wrap_content",
          layout_width: "match_parent", 
          layout_weight: "1",
        
          {
            TextView,
            text: "Find",
            textSize: "17sp",
            gravity: "center",
          },

          {
            EditText,
            id: "find",
            textSize: "18sp",
            singleLine: true,
            paddingLeft: "4dp",
            paddingRight: "4dp",
            layout_height: "52dp",
            layout_weight: "1",
          },
        },
      },

      // REPLACE
      {
        LinearLayout,
        id: "replaceSection",
        visibility: "gone",
        orientation: "vertical",
        layout_width: "match_parent",
        layout_height: "52dp",
        
        {
          LinearLayout,
          orientation: "horizontal",
          layout_height: "wrap_content",
          layout_width: "match_parent", 
          layout_weight: "1",
        
          {
            TextView,
            text: "Rep",
            textSize: "17sp",
            gravity: "center",
          },

          {
            EditText,
            id: "replace",
            textSize: "18sp",
            singleLine: true,
            paddingLeft: "4dp",
            paddingRight: "4dp",
            layout_height: "52dp",
            layout_weight: "1",
          },
        },
      },

      // Separator
      {
        View,
        background: "#414141",
        layout_width: "match_parent",
        layout_height: "1dp",
        layout_marginTop: "8dp",
      },

      // Bottom buttons
      {
        LinearLayout,
        orientation: "horizontal",
        gravity: "center_vertical",
        layout_width: "match_parent",
        layout_height: "58dp",

        {
          TextView,
          id: "btnprev",
          text: "PREV",
          textSize: "17sp",
          gravity: "center",
          clickable: true,
          layout_width: "0dp",
          layout_height: "58dp",
          layout_weight: "1",
        },

        {
          TextView,
          id: "btnnext",
          text: "NEXT",
          textSize: "17sp",
          gravity: "center",
          clickable: true,
          layout_width: "0dp",
          layout_height: "58dp",
          layout_weight: "1",
        },

        {
          TextView,
          id: "btnreplace",
          text: "REP",
          textSize: "17sp",
          gravity: "center",
          clickable: true,
          layout_width: "0dp",
          layout_height: "58dp",
          layout_weight: "1",
        },

        {
          TextView,
          id: "btnall",
          text: "ALL",
          enabled: false,
          textSize: "17sp",
          gravity: "center",
          clickable: true,
          layout_width: "0dp",
          layout_height: "58dp",
          layout_weight: "1",
        },

        {
          ImageView,
          id: "btnmore",
          paddingRight: "10dp",
          colorFilter: theme.text,
          layout_height: "40dp",
          layout_width: "40dp",
          src: "icons/ic_dotsmenu.png",
        },
      },
    },
  }
}