return {
    LinearLayout,
    layout_height: "match_parent",
    layout_width: "match_parent",
    orientation: "vertical",
  
    {
      CardView,
      layout_height: "wrap_content",
      backgroundColor: "#000000",
      radius: "0dp",
      CardElevation: "3dp",
      layout_width: "match_parent",
      
      {
        LinearLayout,
        layout_width: "match_parent",
        layout_marginTop: result,
        {
          LinearLayout,
          orientation: "horizontal",
          gravity: "center",
          layout_height: "56dp",
          layout_width: "match_parent",
          
          {
            LinearLayout,
            layout_height: "match_parent",
            gravity: "center",
            
            {
              CardView,
              layout_height: "80dp",
              PreventCornerOverlap: false,
              layout_marginLeft: "-15dp",
              CardElevation: "0dp",
              radius: "40dp",
              UseCompatPadding: false,
              background: "#00000000",
              layout_width: "80dp",
              {
                ImageView,
                layout_height: "match_parent",
                layout_margin: "-10dp",
                id: "back",
                background: "#00000000",
                padding: "26dp",
                src: "icons/ic_left.png",
                colorFilter: "#FFFFFFFF",
                layout_width: "match_parent",
              },
            },
          },
          
          {
            LinearLayout,
            layout_weight: "1",
            layout_height: "match_parent",
            layout_width: "match_parent",
            gravity: "center|left",
            layout_marginLeft: "-15dp",
            orientation: "vertical",
            {
              TextView,
              singleLine: true,
              text: "Choose source code (*.syp)",
              id: "title",
              textSize: "19dp",
              ellipsize: "end",
              textColor: "#FFFFFF",
            }, 
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-10dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "btnmenu",
              background: "#00000000",
              padding: "20dp",
              src: "icons/menu.png",
              colorFilter: "#FFFFFFFF",
              layout_width: "match_parent",
            },
          },
        },
      },
    },
    {
      LinearLayout,
      layout_height: "match_parent",
      layout_width: "match_parent",
      orientation: "vertical",
      {
        ListView,
        layout_height: "match_parent",
        layout_width: "match_parent",
        layout_margin: "8dp",
        id: "list",
      },
    },
}