return {
  FrameLayout,
  {
    LinearLayout,
    layout_height: "match_parent",
    layout_width: "match_parent",
    orientation: "vertical",
  
    {
      CardView,
      layout_height: "wrap_content",
      backgroundColor: "#1A191C",
      radius: "0dp",
      CardElevation: "3dp",
      layout_width: "match_parent",
      
      {
        LinearLayout,
        layout_width: "match_parent",
        layout_marginTop: result,
        {
          LinearLayout,
          orientation: "horizontal",
          gravity: "center",
          layout_height: "56dp",
          layout_width: "match_parent",
          
          {
            LinearLayout,
            layout_height: "match_parent",
            gravity: "center",
            
            {
              CardView,
              layout_height: "80dp",
              PreventCornerOverlap: false,
              layout_marginLeft: "-15dp",
              CardElevation: "0dp",
              radius: "40dp",
              UseCompatPadding: false,
              background: "#00000000",
              layout_width: "80dp",
              {
                ImageView,
                layout_height: "match_parent",
                layout_margin: "-10dp",
                id: "btn",
                background: "#00000000",
                padding: "26dp",
                src: "icon/navnav.png",
                layout_width: "match_parent",
              },
            },
          },
          
          {
            TextView,
            gravity: "center|left",
            singleLine: true,
            layout_marginLeft: "-15dp",
            layout_width: "match_parent",
            text: activity.getTitle(),
            id: "title",
            textSize: "19dp",
            //ellipsize: "end",
            layout_height: "match_parent",
            layout_weight: "1",
            textColor: "#FFFFFF",
          },
                    {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-17dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "save",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icon/save.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-17dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "undo",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icon/undo.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-19dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "redo",
              background: "#00000000",
              colorFilter: "#FFFFFFFF",
              padding: "20dp",
              src: "icon/redo.png",
              layout_width: "match_parent",
            },
          },
          {
            CardView,
            layout_height: "65dp",
            PreventCornerOverlap: false,
            CardElevation: "0dp",
            layout_marginRight: "-10dp",
            background: "#00000000",
            radius: "33dp",
            UseCompatPadding: false,
            layout_width: "65dp",
            {
              ImageView,
              layout_height: "match_parent",
              layout_margin: "-10dp",
              id: "btnmenu",
              background: "#00000000",
              padding: "20dp",
              src: "icon/abc_ic_menu_moreoverflow_mtrl_alpha.png",
              layout_width: "match_parent",
            },
          },
        },
      },
    },
    {
      LinearLayout,
      layout_height: "match_parent",
      layout_width: "match_parent",
      orientation: "vertical",
      {
        LinearLayout,
        layout_height: "40dp",
        layout_width: "match_parent",
        backgroundColor: "#1E1E1E",
        orientation: "horizontal",
        {
          TextView,
          id: "filename",
          layout_height: "match_parent",
          layout_width: "30%w",
          //layout_weight: "1",
          gravity: "center",
          text: "Home",
          textColor: "#FFFFFF",
          layout_margin: "4dp"
        },
      },
      {
        CodeEditor,
        id: "editor",
        layout_width: "match_parent",
        layout_height: "match_parent",
        textSize: "10sp",
        dark: "true"
      }
    },
  },
  {
    ImageView,
    id: "run",
    src: "icon/run.png",
    layout_width: "54dp",
    layout_height: "54dp",
    layout_gravity: "bottom|right",
    colorFilter: "#FFFFFFFF",
    background: roundedRect("#F85149", 32),
    layout_margin: "16dp"
  }
}